---
version: "3.8"

services:
  frontend:
    image: simple-search-engine-frontend:1
    build: 
      context: ./Simple-Search-Engine-Frontend
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
    # volumes:
    #   - ./Simple-Search-Engine-Frontend:/app
    restart: unless-stopped

  backend:
    image: simple-search-engine-backend:1
    build: ./Simple-Search-Engine-Backend
    ports:
      - 8080:8080
    command: ./docker-entrypoint.sh # override default command in Dockerfile
    # volumes:
    #   - ./Simple-Search-Engine-Backend:/app
    restart: unless-stopped

  database:
    image: mongo:7.0.0-rc10
    ports:
      - 27017:27017
    volumes:
      - simple-search-engine:/data/db # create a volume to persist data
    restart: unless-stopped

volumes:
  simple-search-engine:
...
